const { PrismaClient } = require("../generated/prisma");
const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Iniciando seed...\n");

  // =========================
  // TIEMPO
  // =========================
  console.log("📅 Insertando datos en tabla 'tiempo'...");
  const tiempos = [
    { anio: 2023, mes: 11 },
    { anio: 2023, mes: 12 },
    { anio: 2024, mes: 1 },
    { anio: 2024, mes: 2 },
    { anio: 2024, mes: 3 },
    { anio: 2024, mes: 4 },
    { anio: 2024, mes: 5 },
    { anio: 2024, mes: 6 },
    { anio: 2024, mes: 7 },
    { anio: 2024, mes: 8 },
    { anio: 2024, mes: 9 },
    { anio: 2024, mes: 10 },
    { anio: 2024, mes: 11 },
    { anio: 2024, mes: 12 },
    { anio: 2025, mes: 1 },
    { anio: 2025, mes: 2 },
    { anio: 2025, mes: 3 },
    { anio: 2025, mes: 4 },
    { anio: 2025, mes: 5 },
    { anio: 2025, mes: 6 },
    { anio: 2025, mes: 7 },
    { anio: 2025, mes: 8 },
    { anio: 2025, mes: 9 },
    { anio: 2025, mes: 10 },
  ];
  await prisma.tiempo.createMany({ data: tiempos });
  console.log(`✅ ${tiempos.length} registros insertados en 'tiempo'\n`);

  // =========================
  // PRODUCCION
  // =========================
  console.log("🏭 Insertando datos en tabla 'produccion'...");
  const produccion = [
    {
      id_tiempo: 1,
      horas_produccion: 154,
      horas_improductivas: 34,
      costo_total_produccion: 879024,
      unidades_producidas: 16929,
      unidades_sin_defectos: 15730,
      equipo_con_fallas: "Equipo A",
    },
    {
      id_tiempo: 2,
      horas_produccion: 154,
      horas_improductivas: 19,
      costo_total_produccion: 788862,
      unidades_producidas: 13932,
      unidades_sin_defectos: 12751,
      equipo_con_fallas: "Equipo B",
    },
    {
      id_tiempo: 3,
      horas_produccion: 155,
      horas_improductivas: 35,
      costo_total_produccion: 781076,
      unidades_producidas: 17031,
      unidades_sin_defectos: 15310,
      equipo_con_fallas: "Equipo D",
    },
    {
      id_tiempo: 4,
      horas_produccion: 152,
      horas_improductivas: 32,
      costo_total_produccion: 811907,
      unidades_producidas: 14560,
      unidades_sin_defectos: 12889,
      equipo_con_fallas: "Equipo C",
    },
    {
      id_tiempo: 5,
      horas_produccion: 160,
      horas_improductivas: 32,
      costo_total_produccion: 797585,
      unidades_producidas: 17436,
      unidades_sin_defectos: 15749,
      equipo_con_fallas: "Equipo A",
    },
    {
      id_tiempo: 6,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 812773,
      unidades_producidas: 16780,
      unidades_sin_defectos: 15091,
      equipo_con_fallas: "Equipo C",
    },
    {
      id_tiempo: 7,
      horas_produccion: 153,
      horas_improductivas: 32,
      costo_total_produccion: 810155,
      unidades_producidas: 15162,
      unidades_sin_defectos: 13582,
      equipo_con_fallas: "Equipo B",
    },
    {
      id_tiempo: 8,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 802206,
      unidades_producidas: 17436,
      unidades_sin_defectos: 15647,
      equipo_con_fallas: "Equipo D",
    },
    {
      id_tiempo: 9,
      horas_produccion: 160,
      horas_improductivas: 31,
      costo_total_produccion: 797229,
      unidades_producidas: 16820,
      unidades_sin_defectos: 15291,
      equipo_con_fallas: "Equipo B",
    },
    {
      id_tiempo: 10,
      horas_produccion: 160,
      horas_improductivas: 33,
      costo_total_produccion: 789402,
      unidades_producidas: 17204,
      unidades_sin_defectos: 15691,
      equipo_con_fallas: "Equipo A",
    },
    {
      id_tiempo: 11,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 799906,
      unidades_producidas: 16850,
      unidades_sin_defectos: 15249,
      equipo_con_fallas: "Equipo D",
    },
    {
      id_tiempo: 12,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 789214,
      unidades_producidas: 16950,
      unidades_sin_defectos: 15412,
      equipo_con_fallas: "Equipo C",
    },
    {
      id_tiempo: 13,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 796012,
      unidades_producidas: 17020,
      unidades_sin_defectos: 15500,
      equipo_con_fallas: "Equipo D",
    },
    {
      id_tiempo: 14,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 801233,
      unidades_producidas: 16970,
      unidades_sin_defectos: 15491,
      equipo_con_fallas: "Equipo A",
    },
    {
      id_tiempo: 15,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 795500,
      unidades_producidas: 17180,
      unidades_sin_defectos: 15693,
      equipo_con_fallas: "Equipo B",
    },
    {
      id_tiempo: 16,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 792710,
      unidades_producidas: 17200,
      unidades_sin_defectos: 15710,
      equipo_con_fallas: "Equipo C",
    },
    {
      id_tiempo: 17,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 793150,
      unidades_producidas: 17190,
      unidades_sin_defectos: 15685,
      equipo_con_fallas: "Equipo D",
    },
    {
      id_tiempo: 18,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 796230,
      unidades_producidas: 17210,
      unidades_sin_defectos: 15731,
      equipo_con_fallas: "Equipo A",
    },
    {
      id_tiempo: 19,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 794580,
      unidades_producidas: 17205,
      unidades_sin_defectos: 15700,
      equipo_con_fallas: "Equipo B",
    },
    {
      id_tiempo: 20,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 795310,
      unidades_producidas: 17190,
      unidades_sin_defectos: 15685,
      equipo_con_fallas: "Equipo C",
    },
    {
      id_tiempo: 21,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 796880,
      unidades_producidas: 17220,
      unidades_sin_defectos: 15740,
      equipo_con_fallas: "Equipo D",
    },
    {
      id_tiempo: 22,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 795050,
      unidades_producidas: 17180,
      unidades_sin_defectos: 15670,
      equipo_con_fallas: "Equipo A",
    },
    {
      id_tiempo: 23,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 796110,
      unidades_producidas: 17200,
      unidades_sin_defectos: 15710,
      equipo_con_fallas: "Equipo B",
    },
    {
      id_tiempo: 24,
      horas_produccion: 160,
      horas_improductivas: 34,
      costo_total_produccion: 795800,
      unidades_producidas: 17190,
      unidades_sin_defectos: 15685,
      equipo_con_fallas: "Equipo C",
    },
  ];
  await prisma.produccion.createMany({ data: produccion });
  console.log(`✅ ${produccion.length} registros insertados en 'produccion'\n`);

  // =========================
  // VENTAS
  // =========================
  console.log("💰 Insertando datos en tabla 'ventas'...");
  const ventas = [
    {
      id_tiempo: 1,
      ventas_totales: 879024,
      unidades_vendidas: 16500,
      costo_ventas: 615000,
      nuevos_clientes: 25,
      clientes_activos: 120,
    },
    {
      id_tiempo: 2,
      ventas_totales: 788862,
      unidades_vendidas: 13500,
      costo_ventas: 562500,
      nuevos_clientes: 18,
      clientes_activos: 115,
    },
    {
      id_tiempo: 3,
      ventas_totales: 781076,
      unidades_vendidas: 16800,
      costo_ventas: 588000,
      nuevos_clientes: 22,
      clientes_activos: 125,
    },
    {
      id_tiempo: 4,
      ventas_totales: 811907,
      unidades_vendidas: 14200,
      costo_ventas: 497000,
      nuevos_clientes: 20,
      clientes_activos: 118,
    },
    {
      id_tiempo: 5,
      ventas_totales: 797585,
      unidades_vendidas: 17000,
      costo_ventas: 600000,
      nuevos_clientes: 24,
      clientes_activos: 122,
    },
    {
      id_tiempo: 6,
      ventas_totales: 812773,
      unidades_vendidas: 16780,
      costo_ventas: 595000,
      nuevos_clientes: 21,
      clientes_activos: 119,
    },
    {
      id_tiempo: 7,
      ventas_totales: 810155,
      unidades_vendidas: 15162,
      costo_ventas: 540000,
      nuevos_clientes: 19,
      clientes_activos: 116,
    },
    {
      id_tiempo: 8,
      ventas_totales: 802206,
      unidades_vendidas: 17436,
      costo_ventas: 620000,
      nuevos_clientes: 26,
      clientes_activos: 123,
    },
    {
      id_tiempo: 9,
      ventas_totales: 797229,
      unidades_vendidas: 16820,
      costo_ventas: 610000,
      nuevos_clientes: 22,
      clientes_activos: 121,
    },
    {
      id_tiempo: 10,
      ventas_totales: 789402,
      unidades_vendidas: 17204,
      costo_ventas: 615000,
      nuevos_clientes: 23,
      clientes_activos: 122,
    },
    {
      id_tiempo: 11,
      ventas_totales: 799906,
      unidades_vendidas: 16850,
      costo_ventas: 607000,
      nuevos_clientes: 21,
      clientes_activos: 120,
    },
    {
      id_tiempo: 12,
      ventas_totales: 789214,
      unidades_vendidas: 16950,
      costo_ventas: 610000,
      nuevos_clientes: 22,
      clientes_activos: 121,
    },
    {
      id_tiempo: 13,
      ventas_totales: 796012,
      unidades_vendidas: 17020,
      costo_ventas: 615000,
      nuevos_clientes: 23,
      clientes_activos: 123,
    },
    {
      id_tiempo: 14,
      ventas_totales: 801233,
      unidades_vendidas: 16970,
      costo_ventas: 610000,
      nuevos_clientes: 22,
      clientes_activos: 122,
    },
    {
      id_tiempo: 15,
      ventas_totales: 795500,
      unidades_vendidas: 17180,
      costo_ventas: 613000,
      nuevos_clientes: 24,
      clientes_activos: 124,
    },
    {
      id_tiempo: 16,
      ventas_totales: 792710,
      unidades_vendidas: 17200,
      costo_ventas: 615000,
      nuevos_clientes: 23,
      clientes_activos: 123,
    },
    {
      id_tiempo: 17,
      ventas_totales: 793150,
      unidades_vendidas: 17190,
      costo_ventas: 614000,
      nuevos_clientes: 22,
      clientes_activos: 122,
    },
    {
      id_tiempo: 18,
      ventas_totales: 796230,
      unidades_vendidas: 17210,
      costo_ventas: 616000,
      nuevos_clientes: 24,
      clientes_activos: 125,
    },
    {
      id_tiempo: 19,
      ventas_totales: 794580,
      unidades_vendidas: 17205,
      costo_ventas: 615500,
      nuevos_clientes: 23,
      clientes_activos: 124,
    },
    {
      id_tiempo: 20,
      ventas_totales: 795310,
      unidades_vendidas: 17190,
      costo_ventas: 614000,
      nuevos_clientes: 22,
      clientes_activos: 123,
    },
    {
      id_tiempo: 21,
      ventas_totales: 796880,
      unidades_vendidas: 17220,
      costo_ventas: 616500,
      nuevos_clientes: 24,
      clientes_activos: 125,
    },
    {
      id_tiempo: 22,
      ventas_totales: 795050,
      unidades_vendidas: 17180,
      costo_ventas: 613500,
      nuevos_clientes: 23,
      clientes_activos: 123,
    },
    {
      id_tiempo: 23,
      ventas_totales: 796110,
      unidades_vendidas: 17200,
      costo_ventas: 615000,
      nuevos_clientes: 23,
      clientes_activos: 124,
    },
    {
      id_tiempo: 24,
      ventas_totales: 795800,
      unidades_vendidas: 17190,
      costo_ventas: 614500,
      nuevos_clientes: 22,
      clientes_activos: 123,
    },
  ];
  await prisma.ventas.createMany({ data: ventas });
  console.log(`✅ ${ventas.length} registros insertados en 'ventas'\n`);

  // =========================
  // CALIDAD
  // =========================
  console.log("✅ Insertando datos en tabla 'calidad'...");
  const calidad = [
    {
      id_tiempo: 1,
      productos_inspeccionados: 1000,
      productos_no_conformes: 50,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 24,
    },
    {
      id_tiempo: 2,
      productos_inspeccionados: 1200,
      productos_no_conformes: 45,
      reclamos_recibidos: 4,
      tiempo_resolucion_horas: 22,
    },
    {
      id_tiempo: 3,
      productos_inspeccionados: 1100,
      productos_no_conformes: 60,
      reclamos_recibidos: 6,
      tiempo_resolucion_horas: 25,
    },
    {
      id_tiempo: 4,
      productos_inspeccionados: 1150,
      productos_no_conformes: 55,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 5,
      productos_inspeccionados: 1250,
      productos_no_conformes: 50,
      reclamos_recibidos: 4,
      tiempo_resolucion_horas: 22,
    },
    {
      id_tiempo: 6,
      productos_inspeccionados: 1300,
      productos_no_conformes: 65,
      reclamos_recibidos: 7,
      tiempo_resolucion_horas: 26,
    },
    {
      id_tiempo: 7,
      productos_inspeccionados: 1200,
      productos_no_conformes: 55,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 8,
      productos_inspeccionados: 1280,
      productos_no_conformes: 60,
      reclamos_recibidos: 6,
      tiempo_resolucion_horas: 24,
    },
    {
      id_tiempo: 9,
      productos_inspeccionados: 1250,
      productos_no_conformes: 58,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 10,
      productos_inspeccionados: 1300,
      productos_no_conformes: 62,
      reclamos_recibidos: 6,
      tiempo_resolucion_horas: 24,
    },
    {
      id_tiempo: 11,
      productos_inspeccionados: 1280,
      productos_no_conformes: 60,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 12,
      productos_inspeccionados: 1270,
      productos_no_conformes: 59,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 13,
      productos_inspeccionados: 1290,
      productos_no_conformes: 61,
      reclamos_recibidos: 6,
      tiempo_resolucion_horas: 24,
    },
    {
      id_tiempo: 14,
      productos_inspeccionados: 1300,
      productos_no_conformes: 60,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 24,
    },
    {
      id_tiempo: 15,
      productos_inspeccionados: 1280,
      productos_no_conformes: 58,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 16,
      productos_inspeccionados: 1275,
      productos_no_conformes: 59,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 17,
      productos_inspeccionados: 1290,
      productos_no_conformes: 60,
      reclamos_recibidos: 6,
      tiempo_resolucion_horas: 24,
    },
    {
      id_tiempo: 18,
      productos_inspeccionados: 1300,
      productos_no_conformes: 61,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 24,
    },
    {
      id_tiempo: 19,
      productos_inspeccionados: 1285,
      productos_no_conformes: 59,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 20,
      productos_inspeccionados: 1275,
      productos_no_conformes: 58,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 21,
      productos_inspeccionados: 1290,
      productos_no_conformes: 60,
      reclamos_recibidos: 6,
      tiempo_resolucion_horas: 24,
    },
    {
      id_tiempo: 22,
      productos_inspeccionados: 1280,
      productos_no_conformes: 59,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 23,
      productos_inspeccionados: 1275,
      productos_no_conformes: 58,
      reclamos_recibidos: 5,
      tiempo_resolucion_horas: 23,
    },
    {
      id_tiempo: 24,
      productos_inspeccionados: 1290,
      productos_no_conformes: 60,
      reclamos_recibidos: 6,
      tiempo_resolucion_horas: 24,
    },
  ];
  await prisma.calidad.createMany({ data: calidad });
  console.log(`✅ ${calidad.length} registros insertados en 'calidad'\n`);

  // =========================
  // LOGISTICA
  // =========================
  console.log("🚚 Insertando datos en tabla 'logistica'...");
  const logistica = [
    {
      id_tiempo: 1,
      total_pedidos: 500,
      pedidos_entregados_a_tiempo: 480,
      tiempo_entrega_dias: 2.5,
      costo_logistico_total: 50000,
      unidades_enviadas: 5000,
    },
    {
      id_tiempo: 2,
      total_pedidos: 520,
      pedidos_entregados_a_tiempo: 500,
      tiempo_entrega_dias: 2.7,
      costo_logistico_total: 52000,
      unidades_enviadas: 5200,
    },
    {
      id_tiempo: 3,
      total_pedidos: 530,
      pedidos_entregados_a_tiempo: 510,
      tiempo_entrega_dias: 2.6,
      costo_logistico_total: 53000,
      unidades_enviadas: 5300,
    },
    {
      id_tiempo: 4,
      total_pedidos: 510,
      pedidos_entregados_a_tiempo: 490,
      tiempo_entrega_dias: 2.5,
      costo_logistico_total: 51000,
      unidades_enviadas: 5100,
    },
    {
      id_tiempo: 5,
      total_pedidos: 525,
      pedidos_entregados_a_tiempo: 505,
      tiempo_entrega_dias: 2.8,
      costo_logistico_total: 52500,
      unidades_enviadas: 5250,
    },
    {
      id_tiempo: 6,
      total_pedidos: 530,
      pedidos_entregados_a_tiempo: 510,
      tiempo_entrega_dias: 2.7,
      costo_logistico_total: 53000,
      unidades_enviadas: 5300,
    },
    {
      id_tiempo: 7,
      total_pedidos: 515,
      pedidos_entregados_a_tiempo: 495,
      tiempo_entrega_dias: 2.6,
      costo_logistico_total: 51500,
      unidades_enviadas: 5150,
    },
    {
      id_tiempo: 8,
      total_pedidos: 520,
      pedidos_entregados_a_tiempo: 500,
      tiempo_entrega_dias: 2.7,
      costo_logistico_total: 52000,
      unidades_enviadas: 5200,
    },
    {
      id_tiempo: 9,
      total_pedidos: 525,
      pedidos_entregados_a_tiempo: 505,
      tiempo_entrega_dias: 2.8,
      costo_logistico_total: 52500,
      unidades_enviadas: 5250,
    },
    {
      id_tiempo: 10,
      total_pedidos: 530,
      pedidos_entregados_a_tiempo: 510,
      tiempo_entrega_dias: 2.9,
      costo_logistico_total: 53000,
      unidades_enviadas: 5300,
    },
    {
      id_tiempo: 11,
      total_pedidos: 520,
      pedidos_entregados_a_tiempo: 500,
      tiempo_entrega_dias: 2.7,
      costo_logistico_total: 52000,
      unidades_enviadas: 5200,
    },
    {
      id_tiempo: 12,
      total_pedidos: 525,
      pedidos_entregados_a_tiempo: 505,
      tiempo_entrega_dias: 2.8,
      costo_logistico_total: 52500,
      unidades_enviadas: 5250,
    },
    {
      id_tiempo: 13,
      total_pedidos: 530,
      pedidos_entregados_a_tiempo: 510,
      tiempo_entrega_dias: 2.9,
      costo_logistico_total: 53000,
      unidades_enviadas: 5300,
    },
    {
      id_tiempo: 14,
      total_pedidos: 520,
      pedidos_entregados_a_tiempo: 500,
      tiempo_entrega_dias: 2.7,
      costo_logistico_total: 52000,
      unidades_enviadas: 5200,
    },
    {
      id_tiempo: 15,
      total_pedidos: 525,
      pedidos_entregados_a_tiempo: 505,
      tiempo_entrega_dias: 2.8,
      costo_logistico_total: 52500,
      unidades_enviadas: 5250,
    },
    {
      id_tiempo: 16,
      total_pedidos: 530,
      pedidos_entregados_a_tiempo: 510,
      tiempo_entrega_dias: 2.9,
      costo_logistico_total: 53000,
      unidades_enviadas: 5300,
    },
    {
      id_tiempo: 17,
      total_pedidos: 520,
      pedidos_entregados_a_tiempo: 500,
      tiempo_entrega_dias: 2.7,
      costo_logistico_total: 52000,
      unidades_enviadas: 5200,
    },
    {
      id_tiempo: 18,
      total_pedidos: 525,
      pedidos_entregados_a_tiempo: 505,
      tiempo_entrega_dias: 2.8,
      costo_logistico_total: 52500,
      unidades_enviadas: 5250,
    },
    {
      id_tiempo: 19,
      total_pedidos: 530,
      pedidos_entregados_a_tiempo: 510,
      tiempo_entrega_dias: 2.9,
      costo_logistico_total: 53000,
      unidades_enviadas: 5300,
    },
    {
      id_tiempo: 20,
      total_pedidos: 520,
      pedidos_entregados_a_tiempo: 500,
      tiempo_entrega_dias: 2.7,
      costo_logistico_total: 52000,
      unidades_enviadas: 5200,
    },
    {
      id_tiempo: 21,
      total_pedidos: 525,
      pedidos_entregados_a_tiempo: 505,
      tiempo_entrega_dias: 2.8,
      costo_logistico_total: 52500,
      unidades_enviadas: 5250,
    },
    {
      id_tiempo: 22,
      total_pedidos: 530,
      pedidos_entregados_a_tiempo: 510,
      tiempo_entrega_dias: 2.9,
      costo_logistico_total: 53000,
      unidades_enviadas: 5300,
    },
    {
      id_tiempo: 23,
      total_pedidos: 520,
      pedidos_entregados_a_tiempo: 500,
      tiempo_entrega_dias: 2.7,
      costo_logistico_total: 52000,
      unidades_enviadas: 5200,
    },
    {
      id_tiempo: 24,
      total_pedidos: 525,
      pedidos_entregados_a_tiempo: 505,
      tiempo_entrega_dias: 2.8,
      costo_logistico_total: 52500,
      unidades_enviadas: 5250,
    },
  ];
  await prisma.logistica.createMany({ data: logistica });
  console.log(`✅ ${logistica.length} registros insertados en 'logistica'\n`);

  console.log("🎉 Seed completado exitosamente!");
}

main()
  .catch((e) => {
    console.error("❌ Error durante el seed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
